language: d
dist: bionic

addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - build-essential
    - checkinstall
    - zlib1g-dev
    - mesa-common-dev

before_install:
  - ./install_libmathgl.sh
  
install:
  - mkdir bin

matrix:
  include:
    - d: dmd-2.092.0
    - d: dmd-2.091.1
    - d: dmd-2.090.0
    - d: dmd-2.089.1
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: ldc-1.21.0
    - d: ldc-1.20.1
    - d: ldc-1.19.0
    - d: ldc-1.18.0
    - d: ldc-1.17.0
    - d: ldc-1.16.0
    - d: dmd-nightly
    - d: dmd
    - d: ldc
    - d: dmd-beta
    - d: ldc-beta
  allow_failures:
    - d: dmd-beta
    - d: ldc-beta
    - d: dmd-nightly

script:
  - ./travis.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
