language: d
sudo: false
dist: bionic

before_install:
  - sudo apt update
  - sudo apt install -y libssl-dev build-essential checkinstall zlib1g-dev
  - sudo ./travis_install_deps.sh
  
install:
  - mkdir bin

matrix:
  include:
    - d: dmd-nightly
    - d: dmd-2.089.0
    - d: dmd-2.088.1
    - d: dmd-2.087.1
    - d: ldc-1.18.0
    - d: ldc-1.17.0
    - d: ldc-1.16.0
  allow_failures:
    - d: dmd-nightly

script:
  - ./travis.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
